### ISSUE TITLE
Furigana placed at the wrong locations

### ISSUE THREAD

**Issue by CoffeeMarker** [lingochamp/FuriganaTextView#1] opened 2016-02-22 01:10 UTC
The furigana are placed at the wrong location in the following situations:

There are at least 3 furigana, while the length of the range is smaller than the amount of furigana, and the range starts on the first character of a sentence other than the first sentence. 

So for example, 3 furigana on just the first character of the second sentence.
Furigana(text:"きつね", original: "狐", range NSMakeRange(14,1)) 
//assuming the second sentence starts at 14

There are at least 3 furigana, while the range starts at the last character of the sentence, the range is at least 2 and smaller than the amount of furigana. 

So for example 3 furigana on the last character of the first sentence with a range that is 2 long.
Furigana(text:"さしみ", original: "刺身", range NSMakeRange(13,2)) 
//assuming the second sentence starts at 14

**Comment by eyeplum** [comment] 2016-02-24 03:39
Hi @CoffeeMarker ,

Thank you very much for your feedback.

I tried to add a new sentence and its furiganas according to your description:

``` swift
// Furigana for New Sentence
Furigana(text: "さしみ", original: "刺身", range: NSMakeRange(46, 2)),
Furigana(text: "きつね", original: "狐", range: NSMakeRange(48, 1)),

// New Sentence
contents.appendAttributedString(NSAttributedString(string: "サーモン刺身狐、哺乳綱ネコ目（食肉目）イヌ科イヌ亜科の一部。", attributes: [NSFontAttributeName : exampleFont]))
```

Unfortunately, I can't find a way to reproduce this issue. 

You can find the code above in the `bug_reproduce` branch.

If you can find a way to reproduce the issue, please let me know.

Thanks.

**Comment by eyeplum** [comment] 2016-02-24 03:46
@CoffeeMarker Also, I find that your example furiganas may have incorrect ranges:

``` Swift
Furigana(text:"さしみ", original: "刺身", range NSMakeRange(13,2)),
Furigana(text:"きつね", original: "狐", range NSMakeRange(14,1)),
```

You see, if `刺身` is at location `13`, then any other words after `刺身` can't actually be at location `14`, because the character at `14` is actually `身` (where the character at `13` is `刺`).

So, if I'm understanding the problem correctly, your example may need to be changed to this:

``` Swift
Furigana(text:"さしみ", original: "刺身", range NSMakeRange(13,2)),
Furigana(text:"きつね", original: "狐", range NSMakeRange(15,1)),  // the furigana for '狐' must be at location 15 because the character is actually at 15
```

You can change your code and see if the furiganas is displayed in the right location.

**Comment by CoffeeMarker** [comment] 2016-02-24 08:14
@eyeplum 
Thank you for looking into this bug.

Regarding you last comment, sorry for not clearly mentioning this in the first comment, but those Furigana ranges were tested separately, so overlap of the ranges is not the cause of the bug.

**Comment by eyeplum** [comment] 2016-02-24 09:38
#2 Reproduced on iPhone 4S

**Comment by eyeplum** [comment] 2016-02-24 10:19
@CoffeeMarker I've just committed a quick fix on the `bug_reproduce` branch. 

Please try it and see if the fix works.

Btw, as far as I've observed, the problem is caused by line breaking. When TextKit asks whether it should break a line at a certain position, we used this method to check if the position is in the middle of a `kFuriganaAttributeName`:

``` Swift
func attribute(_ attrName: String, atIndex location: Int, effectiveRange range: NSRangePointer) -> AnyObject?
```

But it turns out that this method sometimes may give us a range shorter than the maximum attribute range. Thus the check may fail to find out that the position is actually in the middle of a `kFuriganaAttributeName`.

The fix is quite easy, we just need to switch to a more accurate method:

``` Swift
func attribute(_ attrName: String, atIndex location: Int, longestEffectiveRange range: NSRangePointer, inRange rangeLimit: NSRange) -> AnyObject?
```

as Apple advised in the document:

> The range isn’t necessarily the maximum range covered by attributeName, and its extent is implementation-dependent. If you need the maximum range, use attribute:atIndex:longestEffectiveRange:inRange:.

**Comment by CoffeeMarker** [comment] 2016-02-24 11:47
Ok, great, I tested it rigorously, and it does seem to be fixed now.

Thank you.

**Closed as completed** 2016-02-24 11:47 UTC

**Comment by eyeplum** [comment] 2016-02-24 15:07
No problem.

I've updated the `master` branch, or if you use `Carthage`, you can use the latest version `0.3.0`.

Thank your so much for your feedback, it really helps!
